# Generated by Django 4.1.2 on 2023-01-26 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0018_auto_20220105_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, related_name='some', to='weblog.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2023, 1, 26, 13, 2, 29, 650883, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 26, 13, 2, 29, 647137, tzinfo=datetime.timezone.utc)),
        ),
    ]
