# Generated by Django 4.1.2 on 2023-01-30 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0019_alter_comment_child_alter_comment_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2023, 1, 30, 10, 13, 33, 691458, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 30, 10, 13, 33, 687605, tzinfo=datetime.timezone.utc)),
        ),
    ]
